20.12.23 gradlew test#7
> Task :compileTestJava FAILED
/home/ec2-user/app/step1/AnimalSalon/src/test/java/com/cndsalon/service/book/BookingTest.java:14:
error: package lombok.extern.slf4j does not exist
import lombok.extern.slf4j.Slf4j;
                          ^
/home/ec2-user/app/step1/AnimalSalon/src/test/java/com/cndsalon/service/book/BookingTest.java:18:
error: cannot find symbol
@Slf4j
 ^
  symbol: class Slf4j
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileTestJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or
--debug option to get more log output. Run with --scan to get full
insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it
incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6.1/userguide/command_line_interface.html#sec:command_line_warnings