20.12.23 gradlew test#4 > Task :compileJava /home/ec2-user/app/step1/AnimalSalon/src/main/java/com/cndsalon/domain/member/CustomUser.java:13: warning: Not generating toString(): A method with that name already exists @ToString ^ Note: Some input files use unchecked or unsafe operations. Note: Recompile with -Xlint:unchecked for details. 1 warning
> Task :compileTestJava
/home/ec2-user/app/step1/AnimalSalon/src/test/java/com/cndsalon/repository/member/HasPwdChk.java:12:
error: package lombok.extern.slf4j does not exist
import lombok.extern.slf4j.Slf4j;
                          ^
/home/ec2-user/app/step1/AnimalSalon/src/test/java/com/cndsalon/repository/member/HasPwdChk.java:15:
error: cannot find symbol
@Slf4j
 ^
  symbol: class Slf4j
/home/ec2-user/app/step1/AnimalSalon/src/test/java/com/cndsalon/repository/member/MemberMybatisTest.java:11:
error: package lombok.extern.slf4j does not exist
import lombok.extern.slf4j.Slf4j;
                          ^
/home/ec2-user/app/step1/AnimalSalon/src/test/java/com/cndsalon/repository/member/MemberMybatisTest.java:14:
error: cannot find symbol
@Slf4j
 ^
  symbol: class Slf4j
/home/ec2-user/app/step1/AnimalSalon/src/test/java/com/cndsalon/repository/member/registerMemberTest_hashedPwd.java:11:
error: package lombok.extern.slf4j does not exist
import lombok.extern.slf4j.Slf4j;
                          ^
/home/ec2-user/app/step1/AnimalSalon/src/test/java/com/cndsalon/repository/member/registerMemberTest_hashedPwd.java:14:
error: cannot find symbol
@Slf4j
 ^
  symbol: class Slf4j
/home/ec2-user/app/step1/AnimalSalon/src/test/java/com/cndsalon/service/book/BookingTest.java:14:
error: package lombok.extern.slf4j does not exist
import lombok.extern.slf4j.Slf4j;
                          ^
/home/ec2-user/app/step1/AnimalSalon/src/test/java/com/cndsalon/service/book/BookingTest.java:18:
error: cannot find symbol
@Slf4j
 ^
  symbol: class Slf4j
/home/ec2-user/app/step1/AnimalSalon/src/test/java/com/cndsalon/service/member/TotalCertificationTest.java:18:
error: package lombok.extern.slf4j does not exist
import lombok.extern.slf4j.Slf4j;
                          ^
/home/ec2-user/app/step1/AnimalSalon/src/test/java/com/cndsalon/service/member/TotalCertificationTest.java:21:
error: cannot find symbol
@Slf4j
 ^
  symbol: class Slf4j
/home/ec2-user/app/step1/AnimalSalon/src/test/java/com/cndsalon/repository/member/HasPwdChk.java:51:
error: cannot find symbol
                        log.info("ID 존재 및 해시 암호 체크");
                        ^
  symbol:   variable log
  location: class HasPwdChk
/home/ec2-user/app/step1/AnimalSalon/src/test/java/com/cndsalon/repository/member/MemberMybatisTest.java:28:
error: cannot find symbol
                log.debug("값 확인 : {}",chk);//실행확인 구웃
                ^
  symbol:   variable log
  location: class MemberMybatisTest
/home/ec2-user/app/step1/AnimalSalon/src/test/java/com/cndsalon/service/member/TotalCertificationTest.java:43:
error: cannot find symbol
                log.debug("mail send 실행");
                ^
  symbol:   variable log
  location: class TotalCertificationTest
13 errors

> Task :compileTestJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileTestJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or
--debug option to get more log output. Run with --scan to get full
insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it
incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 57s
5 actionable tasks: 5 executed
[ec2-user@cndsalon AnimalSalon]$ git pull
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 9 (delta 0), reused 9 (delta 0), pack-reused 0
Unpacking objects: 100% (9/9), done.
From https://github.com/happy-sonday/AnimalSalon
   04542ff..8c11fa9  master     -> origin/master
Updating 04542ff..8c11fa9
Fast-forward
 src/test/java/com/cndsalon/repository/member/HasPwdChk.java | 64
----------------------------------------------------------------
 1 file changed, 64 deletions(-)
 delete mode 100644
src/test/java/com/cndsalon/repository/member/HasPwdChk.java
[ec2-user@cndsalon AnimalSalon]$ ./gradlew test

> Task :compileTestJava FAILED
/home/ec2-user/app/step1/AnimalSalon/src/test/java/com/cndsalon/repository/member/MemberMybatisTest.java:11:
error: package lombok.extern.slf4j does not exist
import lombok.extern.slf4j.Slf4j;
                          ^
/home/ec2-user/app/step1/AnimalSalon/src/test/java/com/cndsalon/repository/member/MemberMybatisTest.java:14:
error: cannot find symbol
@Slf4j
 ^
  symbol: class Slf4j
/home/ec2-user/app/step1/AnimalSalon/src/test/java/com/cndsalon/repository/member/registerMemberTest_hashedPwd.java:11:
error: package lombok.extern.slf4j does not exist
import lombok.extern.slf4j.Slf4j;
                          ^
/home/ec2-user/app/step1/AnimalSalon/src/test/java/com/cndsalon/repository/member/registerMemberTest_hashedPwd.java:14:
error: cannot find symbol
@Slf4j
 ^
  symbol: class Slf4j
/home/ec2-user/app/step1/AnimalSalon/src/test/java/com/cndsalon/service/book/BookingTest.java:14:
error: package lombok.extern.slf4j does not exist
import lombok.extern.slf4j.Slf4j;
                          ^
/home/ec2-user/app/step1/AnimalSalon/src/test/java/com/cndsalon/service/book/BookingTest.java:18:
error: cannot find symbol
@Slf4j
 ^
  symbol: class Slf4j
/home/ec2-user/app/step1/AnimalSalon/src/test/java/com/cndsalon/service/member/TotalCertificationTest.java:18:
error: package lombok.extern.slf4j does not exist
import lombok.extern.slf4j.Slf4j;
                          ^
/home/ec2-user/app/step1/AnimalSalon/src/test/java/com/cndsalon/service/member/TotalCertificationTest.java:21:
error: cannot find symbol
@Slf4j
 ^
  symbol: class Slf4j
/home/ec2-user/app/step1/AnimalSalon/src/test/java/com/cndsalon/repository/member/MemberMybatisTest.java:28:
error: cannot find symbol
                log.debug("값 확인 : {}",chk);//실행확인 구웃
                ^
  symbol:   variable log
  location: class MemberMybatisTest
/home/ec2-user/app/step1/AnimalSalon/src/test/java/com/cndsalon/service/member/TotalCertificationTest.java:43:
error: cannot find symbol
                log.debug("mail send 실행");
                ^
  symbol:   variable log
  location: class TotalCertificationTest
10 errors